
import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author annet
 */
public class Shop_window extends javax.swing.JFrame {

    boolean cloudyBought = false;
    boolean floweryBought = false;
    boolean spaceBought = false;
    boolean edenBought = false;

    Main_window main;


    /**
     * Creates new form Shop_window
     */
    public Shop_window() {
        initComponents();
        getCurrentTheme();
        getCurrentStates();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelСloseMouseClicked = new javax.swing.JLabel();
        jLabelMinMouseClicked = new javax.swing.JLabel();
        jLabelTetris = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelMaximumScore = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        radioButtonGroup = new javax.swing.ButtonGroup();
        jRadioButtonFlowery = new javax.swing.JRadioButton();
        jRadioButtonDefault = new javax.swing.JRadioButton();
        jRadioButtonCloudy = new javax.swing.JRadioButton();
        jRadioButtonSpaceStation = new javax.swing.JRadioButton();
        jRadioButtonEden = new javax.swing.JRadioButton();
        iconSpace = new javax.swing.JLabel();
        iconEden = new javax.swing.JLabel();
        iconCloudy = new javax.swing.JLabel();
        iconDefault = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        iconFlowery = new javax.swing.JLabel();
        priceCloudy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priceFlowery = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceSpace = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        priceEden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(10, 10, 74));

        jLabelСloseMouseClicked.setFont(new java.awt.Font("Centaur", 1, 36)); // NOI18N
        jLabelСloseMouseClicked.setForeground(new java.awt.Color(255, 255, 255));
        jLabelСloseMouseClicked.setText("×");
        jLabelСloseMouseClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelСloseMouseClickedMouseClicked(evt);
            }
        });

        jLabelMinMouseClicked.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 48)); // NOI18N
        jLabelMinMouseClicked.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinMouseClicked.setText("-");
        jLabelMinMouseClicked.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClickedMouseClicked(evt);
            }
        });

        jLabelTetris.setFont(new java.awt.Font("Niagara Engraved", 0, 48)); // NOI18N
        jLabelTetris.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTetris.setText("Tetris");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(164, Short.MAX_VALUE)
                                .addComponent(jLabelTetris, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabelMinMouseClicked)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelСloseMouseClicked)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabelСloseMouseClicked, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelMinMouseClicked, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelTetris))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(10, 10, 74));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(16, 16, 106));

        jLabelMaximumScore.setFont(new java.awt.Font("Sitka Display", 0, 28)); // NOI18N
        jLabelMaximumScore.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaximumScore.setText("Shop");

        jButtonBack.setBackground(new java.awt.Color(255, 0, 102));
        jButtonBack.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("Back");
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(16, 16, 106));




        jRadioButtonFlowery.setBackground(new java.awt.Color(16, 16, 106));
        jRadioButtonFlowery.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jRadioButtonFlowery.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFlowery.setText("Flowery valley");
        jRadioButtonFlowery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFloweryActionPerformed(evt);
            }
        });
        radioButtonGroup.add(jRadioButtonFlowery);



        jRadioButtonDefault.setBackground(new java.awt.Color(16, 16, 106));
        jRadioButtonDefault.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jRadioButtonDefault.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDefault.setText("Default theme ");
        jRadioButtonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDefaultActionPerformed(evt);
            }
        });
        radioButtonGroup.add(jRadioButtonDefault);

        jRadioButtonCloudy.setBackground(new java.awt.Color(16, 16, 106));
        jRadioButtonCloudy.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jRadioButtonCloudy.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCloudy.setText("Cloudy kingdom");
        jRadioButtonCloudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCloudyActionPerformed(evt);
            }
        });
        radioButtonGroup.add(jRadioButtonCloudy);


        jRadioButtonSpaceStation.setBackground(new java.awt.Color(16, 16, 106));
        jRadioButtonSpaceStation.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jRadioButtonSpaceStation.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSpaceStation.setText("Space station");
        jRadioButtonSpaceStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpaceActionPerformed(evt);
            }
        });
        radioButtonGroup.add(jRadioButtonSpaceStation);

        jRadioButtonEden.setBackground(new java.awt.Color(16, 16, 106));
        jRadioButtonEden.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jRadioButtonEden.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEden.setText("Garden of Eden");
        jRadioButtonEden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEdenActionPerformed(evt);
            }
        });
        radioButtonGroup.add(jRadioButtonEden);

        iconSpace.setForeground(new java.awt.Color(255, 255, 255));

        iconEden.setForeground(new java.awt.Color(255, 255, 255));

        iconCloudy.setForeground(new java.awt.Color(255, 255, 255));

        iconDefault.setForeground(new java.awt.Color(255, 255, 255));



        jButton2.setBackground(new java.awt.Color(255, 0, 102));
        jButton2.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 102));
        jButton3.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Buy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 102));
        jButton4.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 0, 102));
        jButton5.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buy");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        iconFlowery.setForeground(new java.awt.Color(255, 255, 255));

        priceCloudy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceCloudy.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("10");

        jLabel2.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("20");

        priceFlowery.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceFlowery.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("40");

        priceSpace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceSpace.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("30");

        priceEden.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceEden.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonEden)
                                        .addComponent(jRadioButtonSpaceStation)
                                        .addComponent(jRadioButtonFlowery)
                                        .addComponent(jRadioButtonCloudy)
                                        .addComponent(jRadioButtonDefault)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(iconCloudy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(iconFlowery, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 25, Short.MAX_VALUE)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(priceFlowery, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(priceCloudy, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(iconDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(iconSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(priceSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(iconEden, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(priceEden, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jRadioButtonDefault)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(iconDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jRadioButtonCloudy)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(16, 16, 16))
                                                        .addComponent(iconCloudy, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(priceCloudy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jRadioButtonFlowery)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButtonSpaceStation)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButtonEden)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(iconFlowery, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(63, 63, 63)
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(priceFlowery, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2))))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(iconSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(65, 65, 65)
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(priceSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel4))))
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(iconEden, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(48, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(priceEden, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3))
                                                                .addGap(78, 78, 78))))))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelMaximumScore)
                                                .addGap(173, 173, 173))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(145, 145, 145))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabelMaximumScore)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BufferedImage planet = null;
        try {
            planet = ImageIO.read(new File("D:\\ideaProjects\\Tetris_game\\Tetris\\Tetris\\src\\planet.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        iconSpace.setIcon(new ImageIcon(planet));

        BufferedImage cloud = null;
        try {
            cloud = ImageIO.read(new File("D:\\ideaProjects\\Tetris_game\\Tetris\\Tetris\\src\\cloudy.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        iconCloudy.setIcon(new ImageIcon(cloud));

        BufferedImage flower = null;
        try {
            flower = ImageIO.read(new File("D:\\ideaProjects\\Tetris_game\\Tetris\\Tetris\\src\\flower.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        iconFlowery.setIcon(new ImageIcon(flower));

        BufferedImage angel = null;
        try {
            angel = ImageIO.read(new File("D:\\ideaProjects\\Tetris_game\\Tetris\\Tetris\\src\\angel.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        iconEden.setIcon(new ImageIcon(angel));

        BufferedImage tetris = null;
        try {
            tetris = ImageIO.read(new File("D:\\ideaProjects\\Tetris_game\\Tetris\\Tetris\\src\\tetris.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        iconDefault.setIcon(new ImageIcon(tetris));

        BufferedImage crystal = null;
        try {
            crystal = ImageIO.read(new File("D:\\ideaProjects\\Tetris_game\\Tetris\\Tetris\\src\\crystal.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        priceCloudy.setIcon(new ImageIcon(crystal));
        priceFlowery.setIcon(new ImageIcon(crystal));
        priceSpace.setIcon(new ImageIcon(crystal));
        priceEden.setIcon(new ImageIcon(crystal));

        pack();
    }// </editor-fold>

    private void jLabelСloseMouseClickedMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    private void jLabelMinMouseClickedMouseClicked(java.awt.event.MouseEvent evt) {
        this.setState(Main_window.ICONIFIED);
    }

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {
        this.dispose();
    }

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jRadioButtonDefaultActionPerformed(java.awt.event.ActionEvent evt) {
        saveTheme("1");
    }

    private void jRadioButtonCloudyActionPerformed(java.awt.event.ActionEvent evt) {
        if(cloudyBought) {
            saveTheme("2");
        }
        else{
            Unavailable_theme warningMessage = new Unavailable_theme();
            warningMessage.setVisible(true);
            warningMessage.pack();
            getCurrentTheme();
        }
    }

    private void jRadioButtonFloweryActionPerformed(java.awt.event.ActionEvent evt) {
        if(floweryBought) {
            saveTheme("3");
        }
        else{
            Unavailable_theme warningMessage = new Unavailable_theme();
            warningMessage.setVisible(true);
            warningMessage.pack();
            getCurrentTheme();
        }
    }

    private void jRadioButtonSpaceActionPerformed(java.awt.event.ActionEvent evt) {
        if(spaceBought) {
            saveTheme("4");
        }
        else{
            Unavailable_theme warningMessage = new Unavailable_theme();
            warningMessage.setVisible(true);
            warningMessage.pack();
            getCurrentTheme();
        }
    }

    private void jRadioButtonEdenActionPerformed(java.awt.event.ActionEvent evt) {
        if(edenBought) {
            saveTheme("5");
        }
        else{
            Unavailable_theme warningMessage = new Unavailable_theme();
            warningMessage.setVisible(true);
            warningMessage.pack();
            getCurrentTheme();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        int cloudyPrice = Integer.parseInt(jLabel1.getText());
        if(getCurrentBalance()<cloudyPrice){
            Not_enough_money warningMessage = new Not_enough_money();
            warningMessage.setVisible(true);
            warningMessage.pack();
        }
        else{
            cloudyBought = true;
            Buy_window purchaseOperation = new Buy_window();
            purchaseOperation.setMainWindow(main);
            purchaseOperation.setTheme(2);
            purchaseOperation.setVisible(true);
            purchaseOperation.pack();
            this.dispose();
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        int floweryPrice = Integer.parseInt(jLabel2.getText());
        if(getCurrentBalance()<floweryPrice){
            Not_enough_money warningMessage = new Not_enough_money();
            warningMessage.setVisible(true);
            warningMessage.pack();
        }
        else{
            floweryBought = true;
            Buy_window purchaseOperation = new Buy_window();
            purchaseOperation.setMainWindow(main);
            purchaseOperation.setTheme(3);
            purchaseOperation.setVisible(true);
            purchaseOperation.pack();
            this.dispose();
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        int spacePrice = Integer.parseInt(jLabel4.getText());
        if(getCurrentBalance()<spacePrice){
            Not_enough_money warningMessage = new Not_enough_money();
            warningMessage.setVisible(true);
            warningMessage.pack();
        }
        else{
            spaceBought = true;
            Buy_window purchaseOperation = new Buy_window();
            purchaseOperation.setMainWindow(main);
            purchaseOperation.setTheme(4);
            purchaseOperation.setVisible(true);
            purchaseOperation.pack();
            this.dispose();
        }
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        int edenPrice = Integer.valueOf(jLabel3.getText());
        if(getCurrentBalance()<edenPrice){
            Not_enough_money warningMessage = new Not_enough_money();
            warningMessage.setVisible(true);
            warningMessage.pack();
        }
        else{
            edenBought = true;
            Buy_window purchaseOperation = new Buy_window();
            purchaseOperation.setMainWindow(main);
            purchaseOperation.setTheme(5);
            purchaseOperation.setVisible(true);
            purchaseOperation.pack();
            this.dispose();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop_window().setVisible(true);
            }
        });
    }

    private void saveTheme(String currentTheme){
        File newFile = new File("D:/tetris_info/Current theme.txt");
        try (BufferedWriter writter = new BufferedWriter(new FileWriter(newFile))) {
            writter.write(currentTheme);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void saveCurrentBalance(String currentBalance){
        File newFile = new File("D:/tetris_info/HowManyCrystals.txt");
        try (BufferedWriter writter = new BufferedWriter(new FileWriter(newFile))) {
            writter.write(currentBalance);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void getCurrentTheme(){
        String currentTheme = "";
        try (BufferedReader reader = Files.newBufferedReader(Paths.get("D:/tetris_info/Current theme.txt"))) {
            currentTheme = reader.readLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
        int intCurrentTheme = Integer.valueOf(currentTheme);
        if(intCurrentTheme==1){
            jRadioButtonDefault.setSelected(true);
        }
        if(intCurrentTheme==2){
            jRadioButtonCloudy.setSelected(true);
        }
        if(intCurrentTheme==3){
            jRadioButtonFlowery.setSelected(true);
        }
        if(intCurrentTheme==4){
            jRadioButtonSpaceStation.setSelected(true);
        }
        if(intCurrentTheme==5){
            jRadioButtonEden.setSelected(true);
        }
    }

    private void getCurrentStates(){
        try (BufferedReader reader = Files.newBufferedReader(Paths.get("D:/tetris_info/Cloudy state.txt"))) {
            cloudyBought = Boolean.valueOf(reader.readLine());
        } catch (IOException e) {
            e.printStackTrace();
        }
        if(cloudyBought){
            jPanel5.remove(jButton2);
            jPanel5.remove(jLabel1);
            jPanel5.remove(priceCloudy);


        }

        try (BufferedReader reader = Files.newBufferedReader(Paths.get("D:/tetris_info/Flowery state.txt"))) {
            floweryBought = Boolean.valueOf(reader.readLine());
        } catch (IOException e) {
            e.printStackTrace();
        }
        if(floweryBought){
            jPanel5.remove(jButton3);
            jPanel5.remove(jLabel2);
            jPanel5.remove(priceFlowery);
        }

        try (BufferedReader reader = Files.newBufferedReader(Paths.get("D:/tetris_info/Space state.txt"))) {
            spaceBought = Boolean.valueOf(reader.readLine());
        } catch (IOException e) {
            e.printStackTrace();
        }
        if(spaceBought){
            jPanel5.remove(jButton4);
            jPanel5.remove(jLabel4);
            jPanel5.remove(priceSpace);
        }

        try (BufferedReader reader = Files.newBufferedReader(Paths.get("D:/tetris_info/Eden state.txt"))) {
            edenBought = Boolean.valueOf(reader.readLine());
        } catch (IOException e) {
            e.printStackTrace();
        }
        if(edenBought){
            jPanel5.remove(jButton5);
            jPanel5.remove(jLabel3);
            jPanel5.remove(priceEden);
        }

    }

    private int getCurrentBalance(){
        String currentBalance = "";
        try (BufferedReader reader = Files.newBufferedReader(Paths.get("D:/tetris_info/HowManyCrystals.txt"))) {
            currentBalance = reader.readLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
        int intCurrentBalance = Integer.valueOf(currentBalance);
        return intCurrentBalance;
    }

    public void setMainWindow(Main_window main){
        this.main = main;
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel iconCloudy;
    private javax.swing.JLabel iconDefault;
    private javax.swing.JLabel iconEden;
    private javax.swing.JLabel iconFlowery;
    private javax.swing.JLabel iconSpace;

    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMaximumScore;
    private javax.swing.JLabel jLabelMinMouseClicked;
    private javax.swing.JLabel jLabelTetris;
    private javax.swing.JLabel jLabelСloseMouseClicked;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonCloudy;
    private javax.swing.JRadioButton jRadioButtonDefault;
    private javax.swing.JRadioButton jRadioButtonEden;
    private javax.swing.JRadioButton jRadioButtonFlowery;
    private javax.swing.JRadioButton jRadioButtonSpaceStation;
    private javax.swing.ButtonGroup radioButtonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceCloudy;
    private javax.swing.JLabel priceEden;
    private javax.swing.JLabel priceFlowery;
    private javax.swing.JLabel priceSpace;
    // End of variables declaration
}

